/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LCD.h"
#include "ROW1_aliases.h"
#include "ROW1.h"
#include "ROW2_aliases.h"
#include "ROW2.h"
#include "ROW3_aliases.h"
#include "ROW3.h"
#include "ROW4_aliases.h"
#include "ROW4.h"
#include "COL1_aliases.h"
#include "COL1.h"
#include "COL2_aliases.h"
#include "COL2.h"
#include "COL3_aliases.h"
#include "COL3.h"
#include "COL4_aliases.h"
#include "COL4.h"
#include "SDAT_1_aliases.h"
#include "SDAT_1.h"
#include "SCLK_1_aliases.h"
#include "SCLK_1.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "SS_aliases.h"
#include "SS.h"
#include "UART.h"
#include "RADAR_aliases.h"
#include "RADAR.h"
#include "timer_clock.h"
#include "Timer.h"
#include "isr_Timer.h"
#include "REED_RELAY_aliases.h"
#include "REED_RELAY.h"
#include "BACKLIGHT_aliases.h"
#include "BACKLIGHT.h"
#include "PWM_BACKLIGHT.h"
#include "pwn1_clk.h"
#include "PWM_BEEPER.h"
#include "beeper_clk.h"
#include "BEEPER_aliases.h"
#include "BEEPER.h"
#include "ADC_SAR_PR.h"
#include "PHRES_aliases.h"
#include "PHRES.h"
#include "EEPROM.h"
#include "UART_GSM.h"
#include "VDAC8.h"
#include "GSM_DTR_aliases.h"
#include "GSM_DTR.h"
#include "UART_ESP.h"
#include "VDAC8_ESP.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "SPIM_IntClock.h"
#include "UART_IntClock.h"
#include "ADC_SAR_PR_IRQ.h"
#include "ADC_SAR_PR_theACLK.h"
#include "UART_GSM_IntClock.h"
#include "UART_ESP_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

